/**
 * Meshy auto-rig + animation clips for a character generated by gen-model.mjs.
 *
 *   node --env-file=.env scripts/rig-model.mjs --name enm-husk --height 1.9 \
 *     --clips "walk:112,attack:97,flinch:178,death:8,idle:0"
 *
 * Reads models-raw/<name>.meshy.json for the refine task id (no re-upload), rigs it
 * (5 credits), then submits one animation task per clip (~3 credits each), downloading
 *   models-raw/<name>@rig.glb        rigged T-pose (the mesh the game loads)
 *   models-raw/<name>@<clip>.glb     rigged mesh + that one animation clip
 * Appends rig/clip task ids to the sidecar. Never logs the key.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const KEY = process.env.MESHY_API_KEY;
if (!KEY || KEY.length < 8) { console.error("MESHY_API_KEY not set"); process.exit(1); }
const HEAD = { Authorization: `Bearer ${KEY}`, "Content-Type": "application/json" };
const RIG = "https://api.meshy.ai/openapi/v1/rigging";
const ANIM = "https://api.meshy.ai/openapi/v1/animations";

const argv = process.argv.slice(2);
const opt = (n, d) => { const i = argv.indexOf(`--${n}`); return i >= 0 ? argv[i + 1] : d; };
const name = opt("name");
const height = parseFloat(opt("height", "1.7"));
const clips = opt("clips", "walk:112,attack:4,flinch:178,death:8,idle:0")
  .split(",").map((s) => { const [label, id] = s.split(":"); return { label, actionId: parseInt(id, 10) }; });
if (!name) { console.error("Missing --name"); process.exit(1); }

const metaPath = join("models-raw", `${name}.meshy.json`);
const meta = JSON.parse(readFileSync(metaPath, "utf8"));
if (!meta.refineId) { console.error(`${metaPath} has no refineId`); process.exit(1); }

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function post(url, body) {
  for (;;) {
    const res = await fetch(url, { method: "POST", headers: HEAD, body: JSON.stringify(body) });
    if (res.status === 429) { await sleep(8000); continue; }
    const text = await res.text();
    if (!res.ok) throw new Error(`POST ${url} ${res.status}: ${text}`);
    return JSON.parse(text);
  }
}

async function poll(url, id, label) {
  let last = -1;
  for (;;) {
    const res = await fetch(`${url}/${id}`, { headers: HEAD });
    if (res.status === 429) { await sleep(8000); continue; }
    const t = await res.json();
    if (t.progress !== last) { process.stdout.write(`\r  ${label}: ${t.status} ${t.progress ?? 0}%   `); last = t.progress; }
    if (t.status === "SUCCEEDED") { process.stdout.write("\n"); return t; }
    if (t.status === "FAILED" || t.status === "CANCELED") { process.stdout.write("\n"); throw new Error(`${label} ${t.status}: ${JSON.stringify(t.task_error || {})}`); }
    await sleep(5000);
  }
}

function glbUrl(task) {
  const direct = task.model_urls?.glb ?? task.model_url ?? task.result?.model_urls?.glb
    ?? task.result?.rigged_character_glb_url ?? task.result?.animation_glb_url;
  if (direct) return direct;
  // fallback: any *.glb url anywhere in result
  for (const v of Object.values(task.result ?? {})) {
    if (typeof v === "string" && v.includes(".glb")) return v;
  }
  return null;
}

async function download(url, dest) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`download ${res.status}`);
  writeFileSync(dest, Buffer.from(await res.arrayBuffer()));
}

console.log(`rig+animate ${name} (height ${height}m, ${clips.length} clips)`);
let rigTaskId = meta.rigTaskId;
if (!rigTaskId) {
  ({ result: rigTaskId } = await post(RIG, { input_task_id: meta.refineId, height_meters: height }));
  console.log(`  rig task: ${rigTaskId}`);
}
const rig = await poll(RIG, rigTaskId, "rig");
const rigGlb = glbUrl(rig);
if (rigGlb) { await download(rigGlb, join("models-raw", `${name}@rig.glb`)); console.log(`  saved ${name}@rig.glb`); }
else console.log(`  rig task keys: ${Object.keys(rig).join(",")} (no glb url found)`);

meta.rigTaskId = rigTaskId;
meta.clips = meta.clips ?? {};
for (const c of clips) {
  let animId = meta.clips[c.label]?.taskId; // already generated — re-download, never re-spend
  if (!animId) ({ result: animId } = await post(ANIM, { rig_task_id: rigTaskId, action_id: c.actionId }));
  const task = await poll(ANIM, animId, `clip ${c.label}`);
  const url = glbUrl(task);
  if (!url) throw new Error(`clip ${c.label}: no glb url; keys=${Object.keys(task).join(",")}`);
  await download(url, join("models-raw", `${name}@${c.label}.glb`));
  meta.clips[c.label] = { taskId: animId, actionId: c.actionId };
  writeFileSync(metaPath, JSON.stringify(meta, null, 2));
  console.log(`  saved ${name}@${c.label}.glb`);
}
writeFileSync(metaPath, JSON.stringify(meta, null, 2));
console.log("done");
